apiVersion: cloud.nicklasfrahm.dev/v1alpha1
kind: Machine
metadata:
  name: aar1swt01
  annotations:
    cloud.nicklasfrahm.dev/vendor: "cisco"
    cloud.nicklasfrahm.dev/model: "n3k-c3048tp-1ge"
spec:
  interfaces:
    mgmt0:
      mac: "60:73:5c:e2:d8:20"
