apiVersion: cloud.nicklasfrahm.dev/v1alpha1
kind: Machine
metadata:
  name: amber
spec:
  bmc:
    interface: bmc
    power:
      type: IPMI
      parameters:
        driver: IPMI2
  interfaces:
    bmc:
      mac: "cc:46:d6:58:9d:ce"
    enp1s0f0:
      mac: "cc:46:d6:58:9d:d4"
      pxe: true
