apiVersion: cloud.nicklasfrahm.dev/v1alpha1
kind: Machine
metadata:
  name: blue
  annotations:
    cloud.nicklasfrahm.dev/vendor: "cisco"
    cloud.nicklasfrahm.dev/model: "ucs-c220-m4"
spec:
  bmc:
    interface: bmc
    power:
      type: IPMI
      parameters:
        driver: IPMI2
      credentials:
        secretRef:
          name: blue-bmc
  interfaces:
    bmc:
      mac: "e4:aa:5d:41:bf:98"
    enp1s0f0:
      mac: "e4:aa:5d:41:bf:9e"
      pxe: true
