apiVersion: cloud.nicklasfrahm.dev/v1alpha1
kind: Machine
metadata:
  name: coral
  annotations:
    cloud.nicklasfrahm.dev/vendor: "hpe"
    cloud.nicklasfrahm.dev/model: "proliant-dl360-gen9"
spec:
  bmc:
    interface: bmc
    power:
      type: IPMI
      parameters:
        driver: IPMI2
      credentials:
        secretRef:
          name: coral-bmc
  interfaces:
    bmc:
      mac: ec:b1:d7:80:3e:86
    eth0:
      mac: ec:b1:d7:74:27:7c
      pxe: true
