apiVersion: cloud.nicklasfrahm.dev/v1alpha1
kind: Machine
metadata:
  name: emerald
spec:
  bmc:
    interface: bmc
    power:
      type: IPMI
      parameters:
        driver: IPMI2
      credentials:
        secretRef:
          name: emerald-ipmi
  interfaces:
    bmc:
      mac: ec:b1:d7:80:3e:ea
    eth0:
      mac: ec:b1:d7:74:77:54
      pxe: true
